# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - space_robot_arm_controller
    - gripper_controller

  space_robot_arm_controller:
    type: FollowJointTrajectory
    joints:
      - link_1_joint
      - link_2_joint
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - left_finger_joint
      - right_finger_joint