controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # forward_position_controller:
    #   type: forward_command_controller/ForwardCommandController

    space_robot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# forward_position_controller:
#   ros__parameters:
#     type: forward_command_controller/ForwardCommandController
#     joints:
#       - link_1_joint
#       - link_2_joint
#     interface_name: position

space_robot_arm_controller:
  ros__parameters:
    joints:
      - link_1_joint
      - link_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      # - velocity