# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    space_robot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

space_robot_arm_controller:
  ros__parameters:
    joints:
      - link_1_joint
      - link_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity